//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAAA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryEnter_
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> idEror { get; set; }
    
        public virtual Eror_ Eror_ { get; set; }
        public virtual Users_ Users_ { get; set; }
        public string lOGG
        {
            get
            {
                return Users_.login;
            }
            set
            {

            }
        }
        public string erorth
        {
            get
            {
                if(Eror_ == null)
                {
                    return " Успешные вход";
                }
                else
                {
                    return Eror_.ErorName;
                }
            }
        }
    }
}
