//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAAA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryResearch_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HistoryResearch_()
        {
            this.Work_analizators_ = new HashSet<Work_analizators_>();
        }
    
        public int id { get; set; }
        public Nullable<int> zakazid { get; set; }
        public Nullable<int> services { get; set; }
    
        public virtual Services_ Services_ { get; set; }
        public virtual Zakaz_ Zakaz_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work_analizators_> Work_analizators_ { get; set; }
        public string servicesName
        {
            get
            {
                if(Services_ == null)
                {
                    return "Потеряшка";
                }
                else
                {
                    return services.ToString();
                }
                
            }
            set
            {

            }
        }
    }
}
