//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAAA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_Box_
    {
        public int id { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> IdCompani { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Users_ Users_ { get; set; }
    }
}
