//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAAA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services_()
        {
            this.HistoryResearch_ = new HashSet<HistoryResearch_>();
        }
    
        public int Code { get; set; }
        public string Service { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CompletionDate { get; set; }
        public Nullable<int> LowerLimitOfNormal { get; set; }
        public Nullable<int> UpperLimitOfNormal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryResearch_> HistoryResearch_ { get; set; }
    }
}
