//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAAA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users_()
        {
            this.HistoryEnter_ = new HashSet<HistoryEnter_>();
            this.Work_analizators_ = new HashSet<Work_analizators_>();
            this.Work_Box_ = new HashSet<Work_Box_>();
            this.Zakaz_ = new HashSet<Zakaz_>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string secondName { get; set; }
        public string thirdName { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<System.DateTime> birthDate { get; set; }
        public string passport { get; set; }
        public string phoneNumber { get; set; }
        public string E_mail { get; set; }
        public Nullable<double> insuranceNumber { get; set; }
        public Nullable<int> insuranceCompany { get; set; }
        public Nullable<int> Role { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryEnter_> HistoryEnter_ { get; set; }
        public virtual insuranceCompany_ insuranceCompany_ { get; set; }
        public virtual Role_ Role_ { get; set; }
        public virtual Type_ Type_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work_analizators_> Work_analizators_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work_Box_> Work_Box_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakaz_> Zakaz_ { get; set; }
        public string FIO
        {
            get
            {

                return $"{firstName} {secondName} {thirdName} ";
            }
            set
            {

            }
        }

    }
}
