//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAAA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_analizators_
    {
        public int id { get; set; }
        public Nullable<int> id_historyResearch { get; set; }
        public Nullable<int> id_analisator { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> time { get; set; }
        public Nullable<int> id_sotrudnilck { get; set; }
        public string Result { get; set; }
    
        public virtual Analizators_ Analizators_ { get; set; }
        public virtual HistoryResearch_ HistoryResearch_ { get; set; }
        public virtual Users_ Users_ { get; set; }
    }
}
