//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAAA1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz_()
        {
            this.HistoryResearch_ = new HashSet<HistoryResearch_>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> statusOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryResearch_> HistoryResearch_ { get; set; }
        public virtual statusOrder_ statusOrder_ { get; set; }
        public virtual Users_ Users_ { get; set; }
        public string Users
        {
            get
            {

                return $"{Users_.firstName} {Users_.secondName} {Users_.thirdName} ";
            }
            set
            {

            }
        }
        public string Status
        {
            get
            {

                return statusOrder_.NameStatus;
            }
            set
            {

            }
        }
    }
}
